#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <vector>

#include "mlp/train/corpus.h"
#include "segmentlib/mlp/dictionary.h"
#include "segmentlib/mlp/vocab.h"

// Sentence → training-example conversion (mlp_module_design.ja.md 3.2): this
// module owns the preprocessing that must match inference bit-for-bit —
// normalization + EGC splitting are delegated to mlp::Vocab::encode (the same
// code the inference encoder uses), vocabulary construction implements the
// frequency threshold of design.ja.md 5.3, and label mapping implements the
// EGC-conflict skip of 5.2/5.5.

namespace segmentlib::mlp::train {

// Dictionary features are generated by the inference-side mlp::DictMatcher
// (its header defines the canonical kDictFeaturesPerDict / DictPosition
// layout), so training and inference produce identical features by
// construction (mlp_impl_design.ja.md III.1).

// Builds the codepoint vocabulary (5.3): counts *normalized* codepoints over
// the corpus and keeps those occurring at least `min_count` times, so
// low-frequency codepoints train the UNK row instead of leaving it at its
// initial value. Sentences with invalid UTF-8 are ignored here; they are
// counted and skipped during example generation.
[[nodiscard]] Vocab build_vocab(std::span<const AnnotatedSentence> sentences,
                                std::uint32_t min_count = 2);

// The corpus converted to training examples. Encoded sentences are kept once
// (flattened CSR); examples are index pairs into them, and windows are
// gathered at batch time (dataset.h) — a few million examples fit comfortably
// in memory this way (mlp_impl_design.ja.md II.5).
//
// The loss mask of II.2 is realized structurally: gaps with Unknown labels
// simply produce no example (a masked example contributes zero loss and zero
// gradient, so dropping it is equivalent and cheaper).
struct ExampleSet {
    std::uint8_t window = 5;    // w: window slots are 2w per example
    std::uint32_t num_dicts = 0;

    // Sentence s owns EGCs [sentence_starts[s], sentence_starts[s+1]);
    // EGC g (global index) owns codepoint rows [egc_starts[g], egc_starts[g+1]).
    std::vector<std::uint32_t> rows;
    std::vector<std::uint32_t> egc_starts;      // size: total EGCs + 1
    std::vector<std::uint32_t> sentence_starts; // size: sentences + 1

    // One example per supervised EGC boundary. `boundary` is the sentence-
    // local gap index: the gap after the sentence's EGC number `boundary`.
    struct Example {
        std::uint32_t sentence;
        std::uint32_t boundary;
        float label;  // 1 = boundary, 0 = no boundary
    };
    std::vector<Example> examples;

    // Active dictionary features per example, CSR (empty ranges everywhere
    // when num_dicts == 0). Indices are sorted and unique (binary clamp, 5.4).
    std::vector<std::uint32_t> feat_offsets;  // size: examples.size() + 1
    std::vector<std::uint32_t> feat_indices;

    [[nodiscard]] std::uint32_t dict_feature_count() const noexcept {
        return num_dicts * kDictFeaturesPerDict;
    }
    [[nodiscard]] std::size_t sentence_count() const noexcept {
        return sentence_starts.empty() ? 0 : sentence_starts.size() - 1;
    }
    // EGC count (M) of sentence s.
    [[nodiscard]] std::uint32_t sentence_egcs(std::uint32_t s) const noexcept {
        return sentence_starts[s + 1] - sentence_starts[s];
    }
    // Constituent codepoint rows of sentence-local EGC `e` of sentence `s`.
    [[nodiscard]] std::span<const std::uint32_t>
    egc_rows(std::uint32_t s, std::uint32_t e) const noexcept {
        const std::uint32_t g = sentence_starts[s] + e;
        return {rows.data() + egc_starts[g], rows.data() + egc_starts[g + 1]};
    }
};

// Preprocessing statistics, reported after example generation (5.5: skip
// counts feed the "正解境界のEGC一致率" check of 5.2).
struct ExampleStats {
    std::size_t sentences_read = 0;
    std::size_t sentences_skipped_conflict = 0;  // boundary inside an EGC
    std::size_t sentences_skipped_invalid = 0;   // invalid UTF-8
    std::size_t boundaries_labeled = 0;          // examples generated
    std::size_t boundaries_unknown = 0;          // unsupervised gaps, no example
};

// Converts corpus sentences into an ExampleSet. `dictionaries` are raw word
// lists (one per dictionary channel); each word is normalized, EGC-split and
// fed to an EGC-unit Aho-Corasick, exactly as the inference loader will do
// (5.7 field 17b), so training and inference produce identical features.
// Sentences whose supervision marks a boundary inside an EGC are skipped with
// a count in `stats` (5.5). A conflicting or invalid sentence contributes no
// examples and no encoded storage.
[[nodiscard]] ExampleSet
build_examples(std::span<const AnnotatedSentence> sentences, const Vocab& vocab,
               std::span<const std::vector<std::string>> dictionaries,
               std::uint8_t window, ExampleStats* stats = nullptr);

}  // namespace segmentlib::mlp::train
