#!/usr/bin/env python3
"""Generates the grapheme-break property table for unicode/egc.

Reads three UCD data files and emits include/segmentlib/unicode/egc_table.inc, a two-stage
lookup table mapping every codepoint to the packed properties the UAX #29
extended-grapheme-cluster rules need:

  - Grapheme_Cluster_Break  (auxiliary/GraphemeBreakProperty.txt)
  - Extended_Pictographic   (emoji/emoji-data.txt)
  - Indic_Conjunct_Break    (DerivedCoreProperties.txt, "InCB")

The packed byte layout and the enum orderings must match
include/segmentlib/unicode/egc.h:

  bits 0-3: GraphemeBreak, bits 4-5: IndicConjunctBreak, bit 6: Ext_Pict

Usage:
  # with a local copy of the UCD files (all three in one directory):
  scripts/gen_egc_table.py --ucd-dir path/to/ucd

  # or let the script download them from unicode.org into --ucd-dir first:
  scripts/gen_egc_table.py --ucd-dir path/to/ucd --download

The generated egc_table.inc is committed to the repository, so this script
only needs to be re-run when upgrading UNICODE_VERSION (update
kEgcUnicodeVersion in egc.h to match, and refresh
tests/data/GraphemeBreakTest.txt from the same UCD version).
"""

import argparse
import re
import sys
import urllib.request
from pathlib import Path

UNICODE_VERSION = "16.0.0"
# major*100 + minor, the encoding design.ja.md 5.7 uses for `unicode_version`.
UNICODE_VERSION_ENCODED = 1600

MAX_CODEPOINT = 0x110000
BLOCK_SIZE = 256

# Must match enum class GraphemeBreak in egc.h.
GCB_VALUES = {
    "Other": 0,  # not listed in the data file; the default
    "CR": 1,
    "LF": 2,
    "Control": 3,
    "Extend": 4,
    "ZWJ": 5,
    "Regional_Indicator": 6,
    "Prepend": 7,
    "SpacingMark": 8,
    "L": 9,
    "V": 10,
    "T": 11,
    "LV": 12,
    "LVT": 13,
}

# Must match enum class IndicConjunctBreak in egc.h.
INCB_VALUES = {"None": 0, "Consonant": 1, "Extend": 2, "Linker": 3}

FILES = {
    "GraphemeBreakProperty.txt": "ucd/auxiliary/GraphemeBreakProperty.txt",
    "emoji-data.txt": "ucd/emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "ucd/DerivedCoreProperties.txt",
}

RANGE_RE = re.compile(r"^([0-9A-Fa-f]{4,6})(?:\.\.([0-9A-Fa-f]{4,6}))?$")


def parse_ucd_lines(path):
    """Yields (first_cp, last_cp, [field, ...]) for each data line."""
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        m = RANGE_RE.match(fields[0])
        if not m:
            raise ValueError(f"{path.name}: unparsable range: {raw!r}")
        first = int(m.group(1), 16)
        last = int(m.group(2), 16) if m.group(2) else first
        yield first, last, fields[1:]


def build_packed_table(ucd_dir):
    packed = bytearray(MAX_CODEPOINT)  # default: Other / None / not pictographic

    for first, last, fields in parse_ucd_lines(ucd_dir / "GraphemeBreakProperty.txt"):
        value = GCB_VALUES[fields[0]]
        for cp in range(first, last + 1):
            packed[cp] |= value

    for first, last, fields in parse_ucd_lines(ucd_dir / "emoji-data.txt"):
        if fields[0] != "Extended_Pictographic":
            continue
        for cp in range(first, last + 1):
            packed[cp] |= 1 << 6

    for first, last, fields in parse_ucd_lines(ucd_dir / "DerivedCoreProperties.txt"):
        if fields[0] != "InCB":
            continue
        value = INCB_VALUES[fields[1]]
        for cp in range(first, last + 1):
            packed[cp] |= value << 4

    return packed


def two_stage(packed):
    """Deduplicates BLOCK_SIZE-byte blocks: returns (stage1 indices, stage2 bytes)."""
    stage1 = []
    stage2 = bytearray()
    block_index = {}
    for start in range(0, MAX_CODEPOINT, BLOCK_SIZE):
        block = bytes(packed[start : start + BLOCK_SIZE])
        idx = block_index.get(block)
        if idx is None:
            idx = len(block_index)
            block_index[block] = idx
            stage2 += block
        stage1.append(idx)
    if len(block_index) > 0xFFFF:
        raise AssertionError("stage1 index no longer fits in uint16")
    return stage1, stage2


def format_array(values, per_line):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + ",".join(str(v) for v in values[i : i + per_line]) + ",")
    return "\n".join(lines)


def emit(stage1, stage2, out_path):
    text = f"""\
// Generated by scripts/gen_egc_table.py from Unicode {UNICODE_VERSION} data.
// DO NOT EDIT. Two-stage lookup: a codepoint's packed grapheme properties are
// kStage2[kStage1[cp >> 8] * {BLOCK_SIZE} + (cp & 0x{BLOCK_SIZE - 1:X})].
// Packed layout (must match egc.h): bits 0-3 GraphemeBreak,
// bits 4-5 IndicConjunctBreak, bit 6 Extended_Pictographic.

inline constexpr std::uint16_t kEgcTableUnicodeVersion = {UNICODE_VERSION_ENCODED};

inline constexpr std::uint16_t kEgcStage1[{len(stage1)}] = {{
{format_array(stage1, 32)}
}};

inline constexpr std::uint8_t kEgcStage2[{len(stage2)}] = {{
{format_array(stage2, 32)}
}};
"""
    out_path.write_text(text, encoding="utf-8")


def download(ucd_dir):
    ucd_dir.mkdir(parents=True, exist_ok=True)
    for name, rel in FILES.items():
        url = f"https://www.unicode.org/Public/{UNICODE_VERSION}/{rel}"
        print(f"fetching {url}")
        urllib.request.urlretrieve(url, ucd_dir / name)


def main():
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ucd-dir", type=Path, required=True,
                        help="directory holding the three UCD data files")
    parser.add_argument("--download", action="store_true",
                        help="download the UCD files into --ucd-dir first")
    parser.add_argument("--out", type=Path,
                        default=repo_root / "include" / "segmentlib" / "unicode" / "egc_table.inc")
    args = parser.parse_args()

    if args.download:
        download(args.ucd_dir)
    missing = [n for n in FILES if not (args.ucd_dir / n).exists()]
    if missing:
        sys.exit(f"missing UCD files in {args.ucd_dir}: {', '.join(missing)} "
                 f"(use --download to fetch them)")

    packed = build_packed_table(args.ucd_dir)
    stage1, stage2 = two_stage(packed)
    emit(stage1, stage2, args.out)
    print(f"wrote {args.out}: {len(stage1)} stage1 entries, "
          f"{len(stage2) // BLOCK_SIZE} unique blocks "
          f"({len(stage1) * 2 + len(stage2)} bytes total)")


if __name__ == "__main__":
    main()
